server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
    resolver 8.8.8.8;
    set $backend "https://be-todo-ooq4.onrender.com";   # ← update this line
    proxy_pass $backend;
    proxy_set_header Host be-todo-ooq4.onrender.com;     # ← and this line
    proxy_set_header X-Real-IP $remote_addr;
    proxy_ssl_server_name on;
}
}