# services:
#   - type: web
#     name: be-todo
#     env: docker
#     dockerfilePath: ./backend/Dockerfile
#     autoDeploy: true
#     envVars:
#       - key: DATABASE_URL
#         value: postgresql://todo_db_0xd1_user:Mauspz5VkyVWesRguhCFVNXXCowFAsoR@dpg-d6rell9j16oc73f6b2dg-a/todo_db_0xd1
#       - key: PORT
#         value: "5001"
    